#!/usr/bin/env bash
# ── BookWorm — Server Bootstrap Script ────────────────────────────────────────
# Run ONCE on a fresh Ubuntu 24.04 VPS as root (or a sudo user).
# What it does:
#   1. Updates the system
#   2. Installs Docker + Docker Compose v2
#   3. Configures UFW firewall (22/SSH, 80/HTTP, 443/HTTPS only)
#   4. Creates a deploy user with Docker access
#   5. Clones the repo into /opt/bookworm
#   6. Generates secure secrets and scaffolds .env.production
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/<YOU>/<REPO>/main/bookworm/scripts/server-setup.sh | sudo bash
#   -- OR --
#   sudo bash bookworm/scripts/server-setup.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

REPO_URL="${REPO_URL:-}"          # set before running: export REPO_URL=https://github.com/you/repo
DEPLOY_USER="${DEPLOY_USER:-bookworm}"
APP_DIR="/opt/bookworm"

echo "════════════════════════════════════════"
echo "  BookWorm Server Setup"
echo "════════════════════════════════════════"

# ── 1. System update ──────────────────────────────────────────────────────────
echo "[1/6] Updating system packages..."
apt-get update -qq
apt-get upgrade -y -qq
apt-get install -y -qq curl git ufw

# ── 2. Install Docker ─────────────────────────────────────────────────────────
echo "[2/6] Installing Docker..."
if ! command -v docker &>/dev/null; then
  curl -fsSL https://get.docker.com | sh
else
  echo "      Docker already installed, skipping."
fi

# Ensure Docker service is enabled and running
systemctl enable --now docker

# ── 3. Firewall ───────────────────────────────────────────────────────────────
echo "[3/6] Configuring UFW firewall..."
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp   comment 'SSH'
ufw allow 80/tcp   comment 'HTTP (Traefik redirect → HTTPS)'
ufw allow 443/tcp  comment 'HTTPS'
ufw --force enable
echo "      UFW status:"
ufw status

# ── 4. Deploy user ────────────────────────────────────────────────────────────
echo "[4/6] Creating deploy user '${DEPLOY_USER}'..."
if id "${DEPLOY_USER}" &>/dev/null; then
  echo "      User already exists, skipping."
else
  useradd -m -s /bin/bash "${DEPLOY_USER}"
  usermod -aG docker "${DEPLOY_USER}"
  # Allow passwordless sudo for deploy commands only
  echo "${DEPLOY_USER} ALL=(ALL) NOPASSWD: /usr/bin/docker, /usr/local/bin/docker" \
    > "/etc/sudoers.d/${DEPLOY_USER}"
  chmod 440 "/etc/sudoers.d/${DEPLOY_USER}"
fi

# ── 5. Clone repo ─────────────────────────────────────────────────────────────
echo "[5/6] Setting up application directory..."
mkdir -p "${APP_DIR}"
if [ -n "${REPO_URL}" ]; then
  if [ -d "${APP_DIR}/.git" ]; then
    echo "      Repo already cloned, pulling latest..."
    git -C "${APP_DIR}" pull
  else
    git clone "${REPO_URL}" "${APP_DIR}"
  fi
else
  echo "      REPO_URL not set — skipping clone."
  echo "      Manually copy your project to ${APP_DIR}/bookworm"
fi
chown -R "${DEPLOY_USER}:${DEPLOY_USER}" "${APP_DIR}"

# ── 6. Scaffold .env.production ───────────────────────────────────────────────
echo "[6/6] Generating secrets and scaffolding .env.production..."
ENV_FILE="${APP_DIR}/bookworm/.env.production"

if [ -f "${ENV_FILE}" ]; then
  echo "      .env.production already exists — not overwriting."
else
  # Generate cryptographically secure secrets
  DB_PASSWORD=$(node -e "process.stdout.write(require('crypto').randomBytes(32).toString('hex'))" 2>/dev/null \
    || openssl rand -hex 32)
  JWT_SECRET=$(node -e "process.stdout.write(require('crypto').randomBytes(64).toString('hex'))" 2>/dev/null \
    || openssl rand -hex 64)
  JWT_REFRESH_SECRET=$(node -e "process.stdout.write(require('crypto').randomBytes(64).toString('hex'))" 2>/dev/null \
    || openssl rand -hex 64)

  cat > "${ENV_FILE}" <<EOF
# Generated by server-setup.sh — fill in DOMAIN and ACME_EMAIL before deploying

DOMAIN=
ACME_EMAIL=

DB_HOST=postgres
DB_PORT=5432
DB_NAME=bookworm
DB_USER=bookworm
DB_PASSWORD=${DB_PASSWORD}

JWT_SECRET=${JWT_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
JWT_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d

NODE_ENV=production
PORT=5000
EOF
  chmod 600 "${ENV_FILE}"
  chown "${DEPLOY_USER}:${DEPLOY_USER}" "${ENV_FILE}"
  echo "      .env.production created at ${ENV_FILE}"
  echo "      ⚠  Edit it now and fill in DOMAIN= and ACME_EMAIL= before running deploy.sh"
fi

echo ""
echo "════════════════════════════════════════"
echo "  Setup complete!"
echo ""
echo "  Next steps:"
echo "  1. Edit ${ENV_FILE}"
echo "     Set DOMAIN=yourdomain.com and ACME_EMAIL=you@example.com"
echo "  2. Point your domain's A record to this server's IP:"
echo "     $(curl -s https://api.ipify.org 2>/dev/null || hostname -I | awk '{print $1}')"
echo "  3. Run:  sudo -u ${DEPLOY_USER} bash ${APP_DIR}/bookworm/scripts/deploy.sh"
echo "════════════════════════════════════════"
